Player.create(name: 'Junichi Sawayashiki',prof_pic: 'JunichiSawayashiki.jpg',login_id:'JunichiSawayashiki',login_pass:'JunichiSawayashiki',description:'JunichiSawayashikiだよ',type_id: 2,rate:100)
Player.create(name: 'Kyotaro Fujimoto',prof_pic: 'KyotaroFujimoto.jpg',login_id:'KyotaroFujimoto',login_pass:'KyotaroFujimoto',description:'KyotaroFujimotoなんだぜ！',type_id: 2,rate:120)
Player.create(name: 'Noboru Uchida',prof_pic: 'NoboruUchida.jpg',login_id:'NoboruUchida',login_pass:'NoboruUchida',description:'NoboruUchidaです',type_id: 2,rate:80)
Player.create(name: 'Syohei Hayashi',prof_pic: 'SyoheiHayashi.jpg',login_id:'SyoheiHayashi',login_pass:'SyoheiHayashi',description:'ぺーたーだよ♡',type_id: 2,rate:330)
Player.create(name: 'Takumu Ito',prof_pic: 'TakumuIto.jpg',login_id:'TakumuIto',login_pass:'TakumuIto',description:'TakumuItoっす',type_id: 2,rate:340)
Player.create(name: 'Yuta Ide',prof_pic: 'YutaIde.jpg',login_id:'YutaIde',login_pass:'YutaIde',description:'YutaIdeマンだよお♡',type_id: 2,rate:325)
Player.create(name: 'Taro Akebono',prof_pic: 'TaroAkebono.jpg',login_id:'TaroAkebono',login_pass:'TaroAkebono',description:'TaroAkebonoだ',type_id: 2,rate:70)
Player.create(name: 'Yoshihisa Inoue',prof_pic: 'YoshihisaInoue.jpg',login_id:'YoshihisaInoue',login_pass:'YoshihisaInoue',description:'YoshihisaInoueです',type_id: 1,rate:150)
Player.create(name: 'Hidekazu Akai',prof_pic: 'HidekazuAkai.jpg',login_id:'HidekazuAkai',login_pass:'HidekazuAkai',description:'HidekazuAkai',type_id: 1,rate:100)
Player.create(name: 'Katsuya Oniduka',prof_pic: 'KatsuyaOniduka.jpg',login_id:'KatsuyaOniduka',login_pass:'KatsuyaOniduka',description:'KatsuyaOniduka',type_id: 1,rate:100)
Player.create(name: 'Nihito Arakawa',prof_pic: 'NihitoArakawa.jpg',login_id:'NihitoArakawa',login_pass:'NihitoArakawa',description:'NihitoArakawaっす',type_id: 1,rate:115)
Player.create(name: 'Seiji Asakawa',prof_pic: 'SeijiAsakawa.jpg',login_id:'SeijiAsakawa',login_pass:'SeijiAsakawa',description:'SeijiAsakawaだ',type_id: 1,rate:110)
Player.create(name: 'Takahiro Aou',prof_pic: 'TakahiroAou.jpg',login_id:'TakahiroAou',login_pass:'TakahiroAou',description:'TakahiroAouです',type_id: 1,rate:95)
Player.create(name: 'Tatsufimi Ito',prof_pic: 'TatsufimiIto.jpg',login_id:'TatsufimiIto',login_pass:'TatsufimiIto',description:'TatsufimiItoじゃ',type_id: 1,rate:145)
Player.create(name: 'Koji Shimizu',prof_pic: 'KojiShimizu.jpg',login_id:'KojiShimizu',login_pass:'KojiShimizu',description:'KojiShimizuマンだよお♡',type_id: 1,rate:315)
Player.create(name: 'Pedoro Takaishi',prof_pic: 'PedoroTakaishi.jpg',login_id:'PedoroTakaishi',login_pass:'PedoroTakaishi',description:'PedoroTakaishiだ',type_id: 3,rate:115)
Player.create(name: 'Attachai Fairtex',prof_pic: 'AttachaiFairtex.jpg',login_id:'AttachaiFairtex',login_pass:'AttachaiFairtex',description:'AttachaiFairtexだよ',type_id: 4,rate:215)


Type.create(type_name: 'pugilistic ')
